apiVersion: v1
kind: Service
metadata:
  name: stubstatus-svc
  namespace: nginx-ingress
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: stubstatus
  selector:
    app: nginx-ingress
