version: "3"

services:
    # Java Monolith Sample Application
    demo:
        container_name: demo
        build: ./demo
        depends_on:
            - db
        ports:
            - "8080:8080"
        volumes:
            - ./demo:/srv
        tty: true
        working_dir: /srv
        environment:
            spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
            spring.datasource.url: "jdbc:mysql://db:3306/demo"
            spring.datasource.username: "mysql"
            spring.datasource.password: "mysql"
            OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
            OTEL_SERVICE_NAME: spring-demo

    # MySQL
    db:
        container_name: db
        build: ./db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: demo
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
            TZ: "Asia/Tokyo"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./db/initdb/:/docker-entrypoint-initdb.d/
        ports:
            - 3306:3306

    # Collector
    otel-collector:
        container_name: otel-collector
        image: otel/opentelemetry-collector-contrib:latest
        command: ["--config=/etc/otel-collector-config.yaml", ""]
        volumes:
            - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
        ports:
            - "1888:1888" # pprof extension
            - "8888:8888" # Prometheus metrics exposed by the collector
            - "8889:8889" # Prometheus exporter metrics
            - "13133:13133" # health_check extension
            - "4317:4317" # OTLP gRPC receiver
            # - '55681:55679' # zpages extension
        depends_on:
            - jaeger
            - zipkin

    # BackEnd

    ## Jaeger
    jaeger:
        container_name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
            - "16686:16686"
            - "14268"
            - "14250"

    ## Zipkin
    zipkin:
        container_name: zipkin
        image: openzipkin/zipkin:latest
        ports:
            - "9411:9411"

    ## Prometheus
    prometheus:
        container_name: prometheus
        image: prom/prometheus:latest
        volumes:
            - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
        ports:
            - "9090:9090"