apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-main
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
      version: v1
  template:
    metadata:
      labels:
        app: main
        version: v1
    spec:
      containers:
      - name: main
        image: registry.gitlab.com/arcadia-application/main-app/mainapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
